# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1939Eh4EjuaB9ouzOq-aQe5kf0ZzRnf25
"""

import pandas as pd
import numpy as np

# 1. SABİTLER
T_cold = 23.0  # Ortam Sıcaklığı (°C)
V_cold = 0.919 # T_cold karşılığı olan voltaj (mV) - K-Type Tablosundan

# 2. ÖLÇÜLEN VERİLER (El yazısı notlarından aktarıldı)
# Not: Zaman aralığı ilk başta düzensiz (1, 3, 6...), sonra düzenli varsayıldı.
data = {
    'Time (s)': [1, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90],
    'Delta_V_mV': [0.04, 4.32, 4.74, 4.89, 5.17, 5.32, 5.46, 5.61, 5.68, 5.73, 5.78,
                   5.82, 5.85, 5.80, 5.81, 5.83, 5.84, 5.86, 5.87, 5.98, 5.89, 5.89,
                   6.00, 6.01, 6.02, 6.02, 6.02, 6.03, 6.03, 6.03, 6.03]
}

df = pd.DataFrame(data)

# 3. K-TIPI TERMOKUPL REFERANS VERİLERİ (Tablodan bir kesit)
# mV değerleri index, Sıcaklık değerleri value olacak şekilde basitleştirilmiş bir lookup serisi
# Aralık: 0°C - 180°C arası veriler (Görseldeki tablodan)
ref_mV = [0.000, 0.397, 0.798, 0.919, 1.203, 1.612, 2.023, 2.436, 2.851, 3.267, 3.682, 4.096,
          4.509, 4.920, 5.328, 5.735, 6.138, 6.540, 6.941, 7.340]
ref_Temp = [0, 10, 20, 23, 30, 40, 50, 60, 70, 80, 90, 100,
            110, 120, 130, 140, 150, 160, 170, 180]

# 4. HESAPLAMA FONKSİYONU
def get_temp_from_voltage(v_target):
    # Doğrusal Enterpolasyon (Linear Interpolation)
    return np.interp(v_target, ref_mV, ref_Temp)

# 5. İŞLEMLER
# V_hot = Delta_V + V_cold
df['V_cold (mV)'] = V_cold
df['V_hot (mV)'] = df['Delta_V_mV'] + df['V_cold (mV)']
df['T_cold (°C)'] = T_cold

# T_hot hesapla
df['T_hot (°C)'] = df['V_hot (mV)'].apply(get_temp_from_voltage)

# Sonucu yuvarla
df['V_hot (mV)'] = df['V_hot (mV)'].round(3)
df['T_hot (°C)'] = df['T_hot (°C)'].round(2)

# Tabloyu göster
print(df.to_markdown(index=False))