# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1939Eh4EjuaB9ouzOq-aQe5kf0ZzRnf25
"""

import pandas as pd
import numpy as np

# 1. PARAMETRELER
T_cold_env = 23.0  # Ortam Sıcaklığı (°C)

# 2. ÖLÇÜLEN VERİLER (Senin defterindeki veriler)
data = {
    'Time (s)': [1, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90],
    'Delta_V_mV': [0.04, 4.32, 4.74, 4.89, 5.17, 5.32, 5.46, 5.61, 5.68, 5.73, 5.78,
                   5.82, 5.85, 5.80, 5.81, 5.83, 5.84, 5.86, 5.87, 5.98, 5.89, 5.89,
                   6.00, 6.01, 6.02, 6.02, 6.02, 6.03, 6.03, 6.03, 6.03]
}
df = pd.DataFrame(data)

# 3. HASSAS K-TIPI TERMOKUPL VERITABANI (0°C - 180°C Arası Tam Sayılar)
# Gönderdiğin tablodaki değerlerdir.
# Index = Sıcaklık (°C), Değer = Voltaj (mV)
k_type_lookup = [
    0.000, 0.039, 0.079, 0.119, 0.158, 0.198, 0.238, 0.277, 0.317, 0.357, # 0-9
    0.397, 0.437, 0.477, 0.517, 0.557, 0.597, 0.637, 0.677, 0.718, 0.758, # 10-19
    0.798, 0.838, 0.879, 0.919, 0.960, 1.000, 1.041, 1.081, 1.122, 1.163, # 20-29 (23°C burada 0.919)
    1.203, 1.244, 1.285, 1.326, 1.366, 1.407, 1.448, 1.489, 1.530, 1.571, # 30-39
    1.612, 1.653, 1.694, 1.735, 1.776, 1.817, 1.858, 1.899, 1.941, 1.982, # 40-49
    2.023, 2.064, 2.106, 2.147, 2.188, 2.230, 2.271, 2.312, 2.354, 2.395, # 50-59
    2.436, 2.478, 2.519, 2.561, 2.602, 2.644, 2.685, 2.727, 2.768, 2.810, # 60-69
    2.851, 2.893, 2.934, 2.976, 3.017, 3.059, 3.100, 3.142, 3.184, 3.225, # 70-79
    3.267, 3.308, 3.350, 3.391, 3.433, 3.474, 3.516, 3.557, 3.599, 3.640, # 80-89
    3.682, 3.723, 3.765, 3.806, 3.848, 3.889, 3.931, 3.972, 4.013, 4.055, # 90-99
    4.096, 4.138, 4.179, 4.220, 4.262, 4.303, 4.344, 4.385, 4.427, 4.468, # 100-109
    4.509, 4.550, 4.591, 4.633, 4.674, 4.715, 4.756, 4.797, 4.838, 4.879, # 110-119
    4.920, 4.961, 5.002, 5.043, 5.084, 5.124, 5.165, 5.206, 5.247, 5.288, # 120-129
    5.328, 5.369, 5.410, 5.450, 5.491, 5.532, 5.572, 5.613, 5.653, 5.694, # 130-139
    5.735, 5.775, 5.815, 5.856, 5.896, 5.937, 5.977, 6.017, 6.058, 6.098, # 140-149
    6.138, 6.179, 6.219, 6.259, 6.299, 6.339, 6.380, 6.420, 6.460, 6.500, # 150-159
    6.540, 6.580, 6.620, 6.660, 6.701, 6.741, 6.781, 6.821, 6.861, 6.901, # 160-169
    6.941, 6.981, 7.021, 7.060, 7.100, 7.140, 7.180, 7.220, 7.260, 7.300  # 170-179
]
# Liste indeksi doğrudan sıcaklığa denk gelir (Örn: k_type_lookup[23] = 0.919)
temps = np.arange(len(k_type_lookup)) # 0, 1, 2, ... 179

# 4. HESAPLAMA FONKSIYONLARI
def get_mV_from_temp(T):
    # Sıcaklıktan Voltaj bulma (V_cold için)
    # T tam sayı ise direkt listeden al, değilse enterpolasyon yap
    return np.interp(T, temps, k_type_lookup)

def get_temp_from_mV(mV):
    # Voltajdan Sıcaklık bulma (T_hot için)
    # Listeyi ters çevirip enterpolasyon yapıyoruz
    return np.interp(mV, k_type_lookup, temps)

# 5. İŞLEMLER
# Adım 1: V_cold hesapla (23 derece için tablodan değer çekiyor)
V_cold_val = get_mV_from_temp(T_cold_env)

# Tabloyu doldur
df['V_cold (mV)'] = V_cold_val
df['V_hot (mV)'] = df['Delta_V_mV'] + df['V_cold (mV)']
df['T_cold (°C)'] = T_cold_env

# Adım 2: T_hot hesapla (V_hot değerini tabloyla karşılaştırıp sıcaklığı buluyor)
df['T_hot (°C)'] = df['V_hot (mV)'].apply(get_temp_from_mV)

# Yuvarlama işlemleri (Rapor için temiz görünsün)
df['V_hot (mV)'] = df['V_hot (mV)'].round(3)
df['T_hot (°C)'] = df['T_hot (°C)'].round(2)

# Sonucu yazdır
print(df.to_markdown(index=False))